### PR TITLE
Css changed and made cast and crew in seperate cols

### PR DESCRIPTION
**Pull request by Deepankar1484**
Hello @roannav, i have changes some spaces in heading. and the cast and crew are now in a manged format then before and there are headers for the same.
please pull my  request.

### CODE REVIEW

**Comment by Deepankar1484** [comment]
Hello @roannav,i hope you are doing great.
I have changed the alignment in crew and cast as it was told that navbar and other color shouldn't be changed. 
So i updat4ed the alignment and js is updated with four functions. 
Please merge this

**Review by roannav — APPROVED** [review]
I undid the changes to default.css since it was breaking some of the other pages' design.   Might incorporate some of those code changes later.

**Comment by roannav** [comment]
@Deepankar1484 Thank you very much for your contribution! 🏆

**Comment by roannav** [comment]
@all-contributors please add @Deepankar1484  for code, design, and ideas

**Comment by Deepankar1484** [comment]
Hey @roannav , Yee thanks bro for merging the request and there was a thing that u can change some theme for the pages a little more. Thanks again

**Comment by roannav** [comment]
Hey @Deepankar1484, if you have some new idea about themes that you'd like to share, kindly create a new issue.  Thanks!

**Pull request merged**
