### PR TITLE
I have added Cypher to the website.

### PR DESCRIPTION
**Pull request by Aadhithya-R-P**
This is my 1st Pull request. I have added Cypher to the database. Hope it gets merged 🙌.

### CODE REVIEW

**Review by roannav — APPROVED** [review]
:+1:

**Comment by roannav** [comment]
@Aadhithya-R-P Thank you very much for your contribution! 🏆

**Comment by roannav** [comment]
@all-contributors please add @Aadhithya-R-P  for code and content

**Comment by Aadhithya-R-P** [comment]
Thank You very much!!

**Pull request merged**
