### PR TITLE
feat: added the new feature, wallpapers

### PR DESCRIPTION
**Pull request by lokesh932338**
Have added the new feature, "wallpapers",
kindly merge the PR after reviewing the changes.

### CODE REVIEW

**Review by roannav — APPROVED** [review]
LGTM

**Comment by roannav** [comment]
@lokesh932338 Thank you so much for your creativity and your contribution! :100:

**Comment by roannav** [comment]
@all-contributors please add @lokesh932338  for code, content, design, and ideas

**Comment by lokesh932338** [comment]
Thank you very much for the opportunity.

**Pull request merged**
