### PR TITLE
Added Footer

### PR DESCRIPTION
**Pull request by Sujal-2820**
## Footer with Important Links

I have added a footer to enhance the usability of the website. This footer includes important links that can help users navigate through the content more effectively.

Here's a brief overview of the changes I've made:

### Footer Contents:

- **Link 1:** [Matrix Movies Website GitHub Repo] (https://github.com/roannav/matrix-movies-website-hacktoberfest)
- **Link 2:** [Terms of Use] (terms-of-use.html)
- **Link 3:** [Privacy Policy] (privacy-policy.html)

image

### Why This Change?

The addition of these links in the footer will provide quick access to essential information, improving the user experience and helping users find what they're looking for more efficiently.

@roannav Please review and consider merging this pull request. Your feedback is greatly appreciated.

Thank you!

### CODE REVIEW

**Review by roannav — APPROVED** [review]
LGTM

**Comment by roannav** [comment]
Thank you so much for your creativity and your contribution! 🏆

**Comment by Sujal-2820** [comment]
Wooh!! Thanks @roannav for Merging the PR 💯

**Comment by roannav** [comment]
@all-contributors please add @Sujal-2820  for code, design, and ideas

**Pull request merged**
