### PR TITLE
Necessary optimizations ,Matrix theme Font added and other enhancements

### PR DESCRIPTION
**Pull request by aditya4567uk**
-->lowers home loading time by reducing asset load(matrix-background_video.gif)
-->button styled at review page , earlier button had no css
-->all images integrated with lazy loaders which will enable the fast response of website and it contents , hence will enhance user experience.
-->all assets size has been optimized for better loading time and less stress on bandwidth problems. gallery.html , scenes.html etc (heavy pages full of images)
-->global font changed to "Source code pro 4000 regular"
-->characters name aligned center for better readability and UI perspective
-->STRECH of images at scenes.html FIXED.
b1
a1

a3

b3

a2
)

b2

### CODE REVIEW

**Comment by aditya4567uk** [comment]
I hope you''ll like my work , kindly merge it as it has no conflicts & several contributions has been made by me in single row.

THANK YOU FOR YOUR CONSIDERATIONS.

**Review by roannav — APPROVED** [review]
LGTM

**Comment by roannav** [comment]
@aditya4567uk Thank you so much for making the website faster, the new font, new button style, centering the character's names and fixing the squished pictures.  These are some major improvements, so they are greatly appreciated! :100:

**Comment by roannav** [comment]
@all-contributors please add @aditya4567uk  for code, content, design, and ideas

**Pull request merged**
