### PR TITLE
fixed navbar

### LINKED ISSUE #155: Improve navbar
Hey @roannav 
 
I have visited the website and found small bug. 

Screenshot 2023-10-29 155708

As you can see in the above picture the width of the navbar is exceeded.  If we manage the width to the same as its container it will enhance the quality and improves user experience.

### PR DESCRIPTION
**Pull request by sai-kumar0**
## What this PR do

This PR fixes the navbar. The overflown width of the navbar has been fixed

Fixes : #155 

image

I hope you review it and if any issue feel free to text. Below is the link of the fixed one. Try check it 

https://sai-kumar0.github.io/matrix-movies-website-hacktoberfest/

### CODE REVIEW

**Review by roannav — CHANGES_REQUESTED** [review]
@sai-kumar0  I tested your changes but noticed that the same bug still occurs sometimes.  So please try a different way to fix it.  Don't change the padding from 10px to 5px, because that makes the menu items sit too close to each other, so it's hard to read.   Instead, make the menu items wrap to 2 rows earlier (ie before the 1 row starts sticking out past the right edge of the page).

Currently, the code (below) makes the menu items go to 2 rows when the screen width is at 1000px.  Maybe at 1400px is better.
```
@media screen and (max-width: 1000px) {
  .nav .navbar-container {
    display: flex;
    flex-wrap: wrap;
  }
```

Please fix, test, and then git push again to update this pull request.
Thank you.

**Comment by sai-kumar0** [comment]
hey @roannav 

As you suggested the menu items to go to 2 rows when the screen width is 1400px, the change still showing the bug in the wider screens (i.e 1600px ). So I have made the navbar to 2 rows in the initial screens (i.e from 1600px), it won't show the bug in any screen.

Here is the link try check it 

https://sai-kumar0.github.io/matrix-movies-website-hacktoberfest/

**Review by roannav — APPROVED** [review]
@sai-kumar0 Thank you very much for finding, testing, and fixing this bug with the navbar.  Your contribution is appreciated! 🏆

**Comment by roannav** [comment]
@all-contributors please add @sai-kumar0  for bug and code

**Pull request merged**
