### PR TITLE
Added one more character, updated index.html

### PR DESCRIPTION
**Pull request by karansingh1820**

### CODE REVIEW

**Review by roannav — APPROVED** [review]
:+1:

**Comment by roannav** [comment]
@karansingh1820 Thank you very much for your contribution! 🏆

**Comment by roannav** [comment]
@all-contributors please add @karansingh1820 for code and content

**Comment by karansingh1820** [comment]
welcome😊

**Comment by karansingh1820** [comment]
Hello, your repo has been removed from Hacktoberfest why?
It is showing you does not follwing the rules of Hacktoberfest 2023.

**Comment by karansingh1820** [comment]
Hello, your repo has been removed from Hacktoberfest why?
It is showing you does not following the rules of Hacktoberfest 2023.

**Comment by roannav** [comment]
Hello @karansingh1820,

If there is a problem with this repo, that is very concerning.  Can you show me the link, text or screenshot of what you are seeing?  Thank you.

**Comment by karansingh1820** [comment]
Screenshot_20231008-101325_Chrome

**Comment by karansingh1820** [comment]
Screenshot_20231008-101315_Chrome

**Comment by karansingh1820** [comment]
This is showing.

**Comment by roannav** [comment]
@karansingh1820 Thanks, I will try to find out what is happening and remedy this.

**Comment by karansingh1820** [comment]
ok

**Comment by karansingh1820** [comment]
Any update regarding this?

**Comment by roannav** [comment]
@karansingh1820 Good news!  The Hacktoberfest Team has reapproved this repo, so your contribution does count toward Hacktoberfest  :smile:

**Comment by karansingh1820** [comment]
Thank you 😊

**Pull request merged**
