### PR TITLE
Completed Task

### PR DESCRIPTION
**Pull request by karansingh1820**
Added One more Character of Matrix Movie.

### CODE REVIEW

**Review by roannav — COMMENTED** [review]
:+1:

**Comment by roannav** [comment]
@karansingh1820 Hi, thank you for working on this!  :smile: Your code and photo are good.  However, it looks like you closed this pull request, before I could merge it into the main repo.  So it unfortunately has not been accepted yet.  To have your code accepted, please make a new pull request, but this time don't delete your fork at GitHub or close the pull request.  Then I'll merge and close the pull request myself.  Looking forward to your resubmission.

**Comment by karansingh1820** [comment]
Ok Thank you so much. Please give me some time.

**Comment by karansingh1820** [comment]
I have sent you a new pull request again and I have added and updated index.html file, please merge it.

**Pull request closed without merging**
